### ISSUE TITLE
Sample for AspNetMvc5Ef6 can't find SentrySdk

### ISSUE THREAD

**Issue by TimberToe** [getsentry/sentry-dotnet-samples#4]
Steps to reproduce:
 - Download repo
 - Open solution for AspNetMvc5Ef6 (By double clicking on AspNetMvc5Ef6/AspNetMvc5Ef6.sln)
 - Build project
 - You get 2 build errors: "The name 'SentrySdk' does not exist in the current context"

I have .NET 4.7 installed on my system

Minor note: The samples use Sentry 0.0.1-preview2, should'nt they be updated to 1.0.0?

**Comment by bruno-garcia** [comment]
@TimberToe the EntityFramework package hasn't been updated yet.
The issue is being tracked here: https://github.com/getsentry/sentry-dotnet-ef/issues/4

To use the sample please use the versions that are already specified.
We can update the sample once the new EF package is released.

**Comment by TimberToe** [comment]
Ah, I think you missunderstood me. I have not changed anything in the sample.
I only did the steps laid out in the issue description.

I'm honestly not interested in the EntityFramework. We only want to evaluate Sentry to see if it works in our legacy codebase. We don't use EntityFramework in that code.

**Comment by bruno-garcia** [comment]
@TimberToe In this case I'd suggest using [`Sentry` package](https://www.nuget.org/packages/Sentry) directly which is passed preview phase. The EF package needs a bit of work as per the issue I linked before.

I'll make sure the sample is fixed as soon as the EF 1.0.0 is out.

**Comment by bruno-garcia** [comment]
I checked the sample now and it's broken for me too. I'm afraid it has to do with Windows Updates and .NET 4.7.1+

See this thread for more: https://github.com/dotnet/standard/issues/567

We might have to add a target to `Sentry` package for `net461` unfortunately.

**Comment by TimberToe** [comment]
Thank you for looking into it =)

**Comment by bruno-garcia** [comment]
@TimberToe thank you for reporting the issue!

Please let me know how your assessment of Sentry is going.
If you want to chat, I'm online on Sentry's .NET gitter channel: 

https://gitter.im/getsentry/dotnet

**Comment by bruno-garcia** [comment]
@TimberToe I've updated the sample with the latest version.
It worked with my tests but feel free to reopen if you encounter the issue again.
