### ISSUE TITLE
Issues not getting logged?

### ISSUE THREAD

**Issue by stephenmichaelf** [getsentry/sentry-dotnet-samples#9]
I followed the example here:

https://github.com/getsentry/sentry-dotnet-samples/blob/master/AspNetMvc5Ef6/Global.asax.cs

I am able to get a `SentryId` back from `SentrySdk.CaptureException(exception);`

But then in the UI I see nothing under `Issues`.

I also checked the HTTP response with Fiddler and got a 200.

Am I missing something? Are delays expected? How can I debug this further?

cc: @bruno-garcia

**Comment by bruno-garcia** [comment]
Lets track this here: https://github.com/getsentry/sentry-dotnet/issues/518
